### ISSUE TITLE
Do not store zip archives in the repository - provide a link to the original release instead

### ISSUE THREAD

**Issue by alexminza** [maibank/woocommerce-maib#3]
Currently you are distributing an older version of the plugin because of the manual process involved in this "archiving effort" - compare this [wc-moldovaagroindbank.zip history](https://github.com/maibank/woocommerce-maib/commits/main/wc-moldovaagroindbank.zip) with the [original releases history](https://github.com/alexminza/wc-moldovaagroindbank/releases) and [WordPress plugin changelog](https://wordpress.org/plugins/wc-moldovaagroindbank/#developers). Your version is more than a month old!

Instead of manually downloading and maintaining a "backup copy" of the plugin it is much better to help the users by providing a link to the original repository latest release and the official WordPress plugins page:

- https://github.com/alexminza/wc-moldovaagroindbank/releases/latest
- https://wordpress.org/plugins/wc-moldovaagroindbank/

**Comment by alexminza** [comment]
CC @maib-ecomm

**Comment by maib-ecomm** [comment]
ok, deleted zip archive
